FROM  registry.ververica.com/v2.12/flink:1.17.2-stream1-scala_2.12-java11
RUN rm /flink/lib/flink-scala_2.12-1.17.2-stream1.jar
ADD https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.1/scala3-library_3-3.3.1.jar /flink/lib/
ADD https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar /flink/lib/