FROM registry.ververica.com/v2.9/flink:1.15.3-stream1-scala_2.12-java11
# RUN rm /flink/lib/flink-cep-scala_2.12-1.15.3-stream1.jar
# RUN rm /flink/opt/flink-cep-scala_2.12-1.15.3-stream1.jar
RUN rm /flink/lib/flink-scala_2.12-1.15.3-stream1.jar