FROM registry.ververica.com/v2.12/flink:1.18.0-stream1-scala_2.12-java11

## Hadoop Common Classes
# COPY jars/hadoop-common-2.8.3.jar ../lib/
# COPY jars/hadoop-aws-2.8.3.jar ../lib/
# COPY jars/hadoop-common-2.8.3.jar ../lib/
COPY jars/hadoop-mapreduce-client-core-2.8.3.jar ../lib/

## Hadoop AWS Classes
# COPY jars/hadoop-common-2.8.3.jar ../lib/
# COPY jars/commons-logging-1.1.3.jar ../lib

COPY jars/flink-s3-fs-hadoop-1.18.0.jar ../lib/

## AWS Bundled Classes
# COPY jars/bundle-2.20.18.jar ../lib/
# COPY jars/flink-shaded-hadoop-2-uber-1.18.0-stream1.jar ../lib/
# COPY jars/woodstox-core-6.6.0.jar ../lib/

RUN rm -r ../plugins/flink-s3-fs-hadoop
# RUN rm -r ../plugins/flink-gs-fs-hadoop
# RUN rm -r ../plugins/flink-s3-fs-presto
# RUN rm -r ../plugins/flink-azure-fs-hadoop
# RUN rm -r ../plugins/vvc-azure-wi-fs-hadoop